### ISSUE TITLE
Crash on song change.

### ISSUE THREAD

**Issue by KoleckOLP** [Wieku/danser#11]
Hello I have seen someone being able to change the song in the menu of the current danser.
My osu folder is not in the default location and I wasn't able to find a way to change it or import a song. (I assume it's not yet inplemented)

Here is a video(with no audio).
https://streamable.com/jfsi8

**Comment by developomp** [comment]
You're right. danser kotlin version is still a work in progress.
You can use the working (old) version of danser in the meantime.

Here's the repo if you're interested:
https://github.com/Wieku/danser-go

**Comment by Wieku** [comment]
Fixed by 69ad95d
