### ISSUE TITLE
Execution failed for task ':framework:compileKotlin'.

### ISSUE THREAD

**Issue by nyanham** [Wieku/danser#12]
i try to open, and did ./gradlew desktop:run
so this error pop up
[log.txt](https://github.com/Wieku/danser/files/4465616/log.txt)

**Comment by developomp** [comment]
Not entirely sure about this but maybe the Japanese directory name has something to do with it.

**Comment by Wieku** [comment]
@developomp I forgot to answer to that one. Not Japanese names because Java works with that well. Problem lies with `Osu!` dir. Java doesn't like exclamation marks because those are used to refer files inside archive/jar files.
So changing `Osu!` to `Osu` should help.

**Comment by nyanham** [comment]
yeaaah, its worked thx!

**Comment by nyanham** [comment]
i hope we can play with this version as soon!
