### ISSUE TITLE
Is Linux supported?

### ISSUE THREAD

**Issue by developomp** [Wieku/danser#13]
I tried running danser on Linux (Ubuntu 20.04 64bit LTS to be specific) OS but am getting the same error even after several updates.

I cloned the repository through `git clone https://github.com/Wieku/danser.git` in the downloads directory, and ran `./gradlew desktop:run` command.
Osu is not technically "installed" in the system but all the necessary files (beatmaps and skins) are there. I'm playing on ([Osu lazer build](https://github.com/ppy/osu)).

here is the error I'm getting:
```
pomp@pomp:~/Downloads/danser$ ./gradlew desktop:run

> Task :desktop:run FAILED
2020-05-26 21:05:26.816 [main] [Runtime] [INFO]: Window mode changed: Windowed -> Windowed
2020-05-26 21:05:26.818 [main] [Runtime] [INFO]: Window mode changed: Windowed -> Windowed
/usr/lib/jvm/java-11-openjdk-amd64/bin/java: symbol lookup error: /tmp/lwjglpomp/3.2.3-build-13/libbass_fx.so: undefined symbol: BASS_GetVersion

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:run'.
> Process 'command '/usr/lib/jvm/java-11-openjdk-amd64/bin/java'' finished with non-zero exit value 127

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
21 actionable tasks: 1 executed, 20 up-to-date
pomp@pomp:~/Downloads/danser$ 
```

If Linux is not supported, please put which OS is supported in README.md thank you in advance!! <3

**Comment by Wieku** [comment]
Try running with (O)JDK8, not 11.
If it won't help, write you're console output here: #7

**Comment by developomp** [comment]
Nope, it didn't work.
I wrote the console output in #7
