### ISSUE TITLE
and it's all? is there only one "working" button?

### ISSUE THREAD

**Issue by int7bh** [Wieku/danser#14]
![image](https://user-images.githubusercontent.com/68055641/87021704-f5e4a100-c1ee-11ea-99bb-b4380a759b24.png)

**Comment by Wieku** [comment]
Project is in early stage of development.

**Comment by developomp** [comment]
@int7bh maybe what you're looking for is the working version of danser (https://github.com/Wieku/danser-go). This is the one used in Wieku's videos.
