### ISSUE TITLE
The circle around danser is streched on none standard display settings

### ISSUE THREAD

**Issue by JustJass** [Wieku/danser#2]
I changed the display settings to 1080x1080 to avoid the cursor going out of the screen when mirroring them; but doing this, the circle around danser stretch like here :
![danser_2019-06-05_22-21-40](https://user-images.githubusercontent.com/33552504/58987673-46195480-87e0-11e9-9b59-a1ccc822eb42.jpg)

**Comment by Wieku** [comment]
Please post it in Wieku/danser-go
