### ISSUE TITLE
r u srsly?

### ISSUE THREAD

**Issue by az20101** [Wieku/danser#4]
u just closed my question. and you think its a spam.
can you JUST say how to use ur bot.

**Comment by az20101** [comment]
if u will close this issue, that means u wont care about your subscribers and etc.

**Comment by Wieku** [comment]
Please stop burning issue number god dammit. If you had read the description, you can reach me on discord. Not by using tool to report ISSUES!

**Comment by Wieku** [comment]
And it's not bot. It's also mentioned in the video description.

**Comment by Wieku** [comment]
And if you read my message carefully, you are in the wrong repo!

**Comment by Wieku** [comment]
And in the right repo there is a README file!

**Comment by az20101** [comment]
Rewrite of danser-go in Kotlin. More information soon. this is in read me file

**Comment by Wieku** [comment]
Learn to read. You are in the wrong repository

**Comment by Wieku** [comment]
https://github.com/Wieku/danser-go

**Comment by Tanza3D** [comment]
Im about to go insane reading this, god @az20101

**Comment by developomp** [comment]
@az20101 GitHub Karen
