### ISSUE TITLE
Not starting :c

### ISSUE THREAD

**Issue by MarcPlaying** [Wieku/danser#6]
# github.com/go-gl/glfw/v3.1/glfw
In file included from ../../Projects/Proj1/src/github.com/go-gl/glfw/v3.1/glfw/context.go:4:0:
./glfw/include/GLFW/glfw3.h:153:21: fatal error: GL/gl.h: No such file or directory
compilation terminated.
# github.com/go-gl/gl/v3.3-core/gl
../../Projects/Proj1/src/github.com/go-gl/gl/v3.3-core/gl/procaddr.go:52:21: fatal error: GL/glx.h: No such file or directory
compilation terminated

**Comment by Wieku** [comment]
Is it Linux? If so, you need to install libgl

**Comment by MarcPlaying** [comment]
/tmp/go-build889605607/b001/exe/main: error while loading shared libraries: libbass.so: cannot open shared object file: No such file or directory
exit status 12 yet is this here

**Comment by Wieku** [comment]
Oh, i forgot to fix it. Copy libbass.so and libbass_fx.so to /usr/lib directory

**Comment by MarcPlaying** [comment]
Working so lit love go
