### ISSUE TITLE
Game crashes after loading awesomeness

### ISSUE THREAD

**Issue by cchuvakk** [Wieku/danser#9]
> Task :desktop:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':desktop:run'.
> Process 'command 'C:\Program Files\Java\jdk-13.0.1\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
21 actionable tasks: 1 executed, 20 up-to-date

**Comment by Wieku** [comment]
I need more info. Could you give me full console output?

**Comment by Wieku** [comment]
Alternatively you can try running it with JDK8, I don't think Kotlin supports higher Java versions.

**Comment by cchuvakk** [comment]
i will try to run it with jdk8

**Comment by cchuvakk** [comment]
thanks, running it with jdk8 is worked
